# Generated by Django 2.0 on 2020-05-09 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20200429_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discuss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discuss', models.CharField(max_length=512)),
                ('discusstime', models.DateTimeField(auto_now_add=True)),
                ('discussant', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='discuss_user', to='App.User', verbose_name='评论方')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussed_task', to='App.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=512)),
                ('responsetime', models.DateTimeField(auto_now_add=True)),
                ('discuss', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_discuss', to='App.Discuss')),
                ('respondent', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='response_user', to='App.User', verbose_name='回复方')),
            ],
        ),
    ]
