# Generated by Django 2.1.7 on 2020-05-17 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20200517_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='comment_hunter',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='comment_publisher',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='contact_type_hunter',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_hunter', to='App.Contact', verbose_name='委托人联系方式'),
        ),
        migrations.AlterField(
            model_name='task',
            name='contact_type_publisher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_publisher', to='App.Contact', verbose_name='发布人联系方式'),
        ),
        migrations.AlterField(
            model_name='task',
            name='hunter',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hunter', to='App.User', verbose_name='委托人'),
        ),
        migrations.AlterField(
            model_name='task',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='App.User', verbose_name='发布人'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_file',
            field=models.FileField(blank=True, null=True, upload_to='task_file/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_reward',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_sketch',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
