# Generated by Django 2.0.5 on 2020-05-18 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_user_repassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancel_reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_reason', models.CharField(max_length=512, null=True)),
                ('task', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='canceled_tasks', to='App.Task')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_canceled', to='App.User')),
            ],
        ),
    ]
