# Generated by Django 2.1.7 on 2020-05-19 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20200519_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='contact_type_publisher',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_publisher', to='App.Contact', verbose_name='发布人联系方式'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='App.TaskType'),
        ),
    ]
