# Generated by Django 2.1.7 on 2020-04-18 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=32)),
                ('task_sketch', models.CharField(blank=True, max_length=512, null=True)),
                ('task_file', models.FileField(blank=True, null=True, upload_to='static/%Y/%m/%d/')),
                ('ddltime', models.DateField(blank=True, null=True)),
                ('task_reward', models.IntegerField(blank=True, default=0, null=True)),
                ('is_pickedup', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField(default=1)),
                ('typename', models.CharField(max_length=32)),
                ('typesort', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(default='0', max_length=20)),
                ('tel', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('photo', models.ImageField(blank=True, default='static/1.jpg', null=True, upload_to='static/%Y/%m/%d/')),
                ('qq', models.CharField(blank=True, max_length=20, null=True)),
                ('wechat', models.CharField(blank=True, max_length=20, null=True)),
                ('other', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('star', models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='hunter',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hunter', to='hunt.User', verbose_name='委托人'),
        ),
        migrations.AddField(
            model_name='task',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='hunt.User', verbose_name='发布人'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.SET_DEFAULT, to='hunt.TaskType'),
        ),
    ]
