# Generated by Django 2.0.13 on 2020-04-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_for_hunter', models.CharField(max_length=512)),
                ('comment_for_publisher', models.CharField(max_length=512)),
                ('task', models.ForeignKey(on_delete=None, to='hunt.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Revoke_reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revoke_reason', models.CharField(max_length=512)),
                ('task', models.ForeignKey(on_delete=None, to='hunt.Task')),
            ],
        ),
    ]
