# Generated by Django 2.0.5 on 2020-04-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment1', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='d_reason',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='m_mission',
            field=models.ForeignKey(on_delete=None, to='hunt.Task'),
        ),
    ]
