# Generated by Django 2.0.5 on 2020-04-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0002_auto_20200418_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='d_reason',
        ),
        migrations.AddField(
            model_name='task',
            name='reason',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
