# Generated by Django 2.0.13 on 2020-04-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0002_comment_revoke_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_for_hunter',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_for_publisher',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='revoke_reason',
            name='revoke_reason',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
