# Generated by Django 2.0.13 on 2020-04-25 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0003_auto_20200425_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_tasks', to='hunt.Task', unique=True),
        ),
        migrations.AlterField(
            model_name='revoke_reason',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revoked_tasks', to='hunt.Task', unique=True),
        ),
    ]
