# Generated by Django 2.0.5 on 2020-04-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0004_auto_20200426_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt1', models.CharField(max_length=128)),
                ('c_mission', models.ForeignKey(on_delete=None, to='hunt.Task')),
            ],
        ),
    ]
