# Generated by Django 2.0.13 on 2020-04-25 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0004_auto_20200425_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revoke_reason',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revoked_tasks', to='hunt.Task'),
        ),
    ]
