# Generated by Django 2.0.13 on 2020-04-25 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0005_auto_20200425_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_tasks', to='hunt.Task'),
        ),
    ]
