# Generated by Django 2.0.13 on 2020-04-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0006_auto_20200425_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='contact',
            field=models.CharField(default='tel', max_length=32, null=True),
        ),
    ]
