# Generated by Django 2.0.13 on 2020-04-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0007_task_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='contact',
        ),
        migrations.AddField(
            model_name='task',
            name='contacthunter',
            field=models.CharField(default='email', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='contactpublisher',
            field=models.CharField(default='email', max_length=32, null=True),
        ),
    ]
