# Generated by Django 2.1.7 on 2020-04-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0008_auto_20200426_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_file',
            field=models.FileField(blank=True, null=True, upload_to='%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='static/1.jpg', null=True, upload_to='%Y/%m/%d/'),
        ),
    ]
