# Generated by Django 2.1.7 on 2020-04-26 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0009_auto_20200426_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='static/1.jpg', null=True, upload_to='photo/%Y/%m/%d/'),
        ),
    ]
