# Generated by Django 2.0.13 on 2020-04-27 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0010_auto_20200426_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField(default=0)),
                ('typename', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='contacthunter',
        ),
        migrations.RemoveField(
            model_name='task',
            name='contactpublisher',
        ),
        migrations.AddField(
            model_name='task',
            name='comment_for_hunter',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='comment_for_publisher',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reason',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='task',
            name='contact_type_hunter',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_hunter', to='hunt.Contact', verbose_name='委托人联系方式'),
        ),
        migrations.AddField(
            model_name='task',
            name='contact_type_publisher',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_publisher', to='hunt.Contact', verbose_name='发布人联系方式'),
        ),
    ]
