# Generated by Django 2.0.13 on 2020-04-27 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0011_auto_20200428_0021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact1',
        ),
    ]
