# Generated by Django 2.0.13 on 2020-04-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0012_auto_20200428_0156'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact1',
            new_name='Contact',
        ),
    ]
