# Generated by Django 2.1.7 on 2020-04-28 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0013_auto_20200428_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='photo',
            new_name='icon',
        ),
    ]
