# Generated by Django 2.1.7 on 2020-04-28 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0014_auto_20200428_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='contact_type_publisher',
            field=models.ForeignKey(db_constraint=False, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_publisher', to='hunt.Contact', verbose_name='发布人联系方式'),
        ),
    ]
