# Generated by Django 2.1.7 on 2020-04-28 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0015_auto_20200428_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ddltime',
            field=models.DateField(default='2021-09-03'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='hunt.TaskType'),
        ),
    ]
