# Generated by Django 2.0.13 on 2020-04-30 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0018_auto_20200428_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discuss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discuss', models.CharField(max_length=512, null=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_discuss', to='hunt.Discuss')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussed_task', to='hunt.Task')),
            ],
        ),
    ]
