# Generated by Django 2.0.13 on 2020-04-30 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0019_discuss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discuss',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_discuss', to='hunt.Discuss'),
        ),
    ]
