# Generated by Django 2.0.13 on 2020-04-30 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0020_auto_20200501_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='discuss',
            name='discussant',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='discuss_user', to='hunt.User', verbose_name='评论方'),
        ),
    ]
