# Generated by Django 2.0.13 on 2020-04-30 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0021_discuss_discussant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discuss',
            name='discuss',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='discuss',
            name='discussant',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='discuss_user', to='hunt.User', verbose_name='评论方'),
        ),
    ]
