# Generated by Django 2.0.13 on 2020-04-30 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0022_auto_20200501_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discuss',
            name='response',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_discuss', to='hunt.Discuss'),
        ),
        migrations.AlterField(
            model_name='revoke_reason',
            name='task',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='revoked_tasks', to='hunt.Task'),
        ),
    ]
