# Generated by Django 2.0.13 on 2020-04-30 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0023_auto_20200501_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='discuss',
            name='response',
        ),
        migrations.AddField(
            model_name='response',
            name='response',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_discuss', to='hunt.Discuss'),
        ),
    ]
