# Generated by Django 2.0.13 on 2020-04-30 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0024_auto_20200501_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='discuss',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_discuss', to='hunt.Discuss'),
        ),
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.CharField(max_length=512),
        ),
    ]
