# Generated by Django 2.0.13 on 2020-04-30 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0025_auto_20200501_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='respondent',
            field=models.ForeignKey(db_constraint=False, default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='response_user', to='hunt.User', verbose_name='评论方'),
            preserve_default=False,
        ),
    ]
