# Generated by Django 2.1.7 on 2020-05-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0028_auto_20200505_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='repassword',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
