# Generated by Django 2.1.7 on 2020-05-09 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0029_user_repassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='star',
            new_name='rank',
        ),
    ]
