# Generated by Django 2.0.13 on 2020-05-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0030_auto_20200509_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, default='photo/2020/04/26/1.jpg', null=True, upload_to='photo/%Y/%m/%d/'),
        ),
    ]
