# Generated by Django 2.0.13 on 2020-05-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0031_auto_20200509_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_file',
            field=models.FileField(blank=True, null=True, upload_to='static/%Y/%m/%d/'),
        ),
    ]
