# Generated by Django 2.0.5 on 2020-05-09 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0034_auto_20200509_1401'),
        ('hunt', '0005_cnt'),
    ]

    operations = [
    ]
