# Generated by Django 2.0.5 on 2020-05-10 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0035_merge_20200509_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancel_reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_reason', models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cnt',
            name='c_mission',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='m_mission',
        ),
        migrations.AlterField(
            model_name='task',
            name='reason',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='repassword',
            field=models.CharField(max_length=200000, null=True),
        ),
        migrations.DeleteModel(
            name='Cnt',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.AddField(
            model_name='cancel_reason',
            name='task',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='canceled_tasks', to='hunt.Task'),
        ),
        migrations.AddField(
            model_name='cancel_reason',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_canceled', to='hunt.User'),
        ),
    ]
