# Generated by Django 2.0.5 on 2020-05-10 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0036_auto_20200510_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reason',
        ),
    ]
