# Generated by Django 2.0.13 on 2020-05-16 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0037_remove_task_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancel_reason',
            name='task',
        ),
        migrations.RemoveField(
            model_name='cancel_reason',
            name='user',
        ),
        migrations.RemoveField(
            model_name='discuss',
            name='discussant',
        ),
        migrations.RemoveField(
            model_name='discuss',
            name='task',
        ),
        migrations.RemoveField(
            model_name='response',
            name='discuss',
        ),
        migrations.RemoveField(
            model_name='response',
            name='respondent',
        ),
        migrations.RemoveField(
            model_name='revoke_reason',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='contact_type_hunter',
        ),
        migrations.RemoveField(
            model_name='task',
            name='contact_type_publisher',
        ),
        migrations.RemoveField(
            model_name='task',
            name='hunter',
        ),
        migrations.RemoveField(
            model_name='task',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
        migrations.DeleteModel(
            name='Cancel_reason',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Discuss',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.DeleteModel(
            name='Revoke_reason',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskType',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
